{"schema": "https://raw.githubusercontent.com/etalab/lieux-covoiturage/refs/heads/master/schema.json","url": "https://example.com/file","options": {"ignore_header_case": "false"},"error": {"message": "The data source could not be successfully loaded: HTTPConnectionPool(host='example.com', port=443): Max retries exceeded with url: file (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7dd9a6a910>, 'Connection to example.com timed out. (connect timeout=10)'))","type": "source-error"}}
